apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
  labels:
    app: metadata-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-writer
  template:
    metadata:
      labels:
        app: metadata-writer
    spec:
      containers:
      - name: main
       # image: gcr.io/ml-pipeline/metadata-writer:dummy
	image: quay.io/ibm/kubeflow-metadata-writer-ppc64le:1.6.0
        env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: kubeflow-pipelines-metadata-writer
