apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-scheduledworkflow
  name: ml-pipeline-scheduledworkflow
spec:
  selector:
    matchLabels:
      app: ml-pipeline-scheduledworkflow
  template:
    metadata:
      labels:
        app: ml-pipeline-scheduledworkflow
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      containers:
#      - image: gcr.io/ml-pipeline/scheduledworkflow:dummy
      - image: quay.io/ibm/kubeflow-scheduledworkflow-ppc64le:1.5.0	
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-scheduledworkflow
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CRON_SCHEDULE_TIMEZONE
            valueFrom:
              configMapKeyRef:
                name: pipeline-install-config
                key: cronScheduleTimezone
      serviceAccountName: ml-pipeline-scheduledworkflow
